version: '3.8'
services:
  api:
    build: .
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/project_evaluation
    depends_on:
      - db
    networks:
      - project-network

  db:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=project_evaluation
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - project-network

volumes:
  postgres-data:

networks:
  project-network:
    driver: bridge